### PR TITLE
Add collada meshes

### PR DESCRIPTION
**Pull request by bhomberg**
I added the collada meshes that differ between the 7_70 and 5_90 robots and updated to reference the collada files.  It seemed like overkill to add a separate common folder for the shared meshes when there's only 2 robots, but I can switch to that if you'd prefer.

### CODE REVIEW

**Comment by jonbinney** [comment]
@gavanderhoorn we've got both the 7_70 and 5_90 versions of the IRB 1200 robots; is there anything @bhomberg and I can do to help get https://github.com/ros-industrial/abb_experimental/pull/85 ready to merge?

**Comment by gavanderhoorn** [comment]
No. I just need some time to review the changes proposed by @bhomberg.

IIRC, the meshes were the only thing that needed to be sorted out before ros-industrial/abb_experimental#85 could be merged, so if this PR checks out, the other one should be straightforward to merge.

**Comment by gavanderhoorn** [comment]
Just took a quick look and I'm not sure everything is ok here: at first I didn't see any robot after launching `test_irb1200_7_70.launch`. It looks like the `scale` attribute on the `visual` geometry is not needed.

After removing that, the robot was visible, but it looks like the mesh origin and orientation is not entirely correct:

rviz_screenshot_2018_03_23-18_52_46

Did it render like this for you as well @bhomberg?

**Comment by gavanderhoorn** [comment]
Also notice the colour difference between the two sets of meshes. I believe we'll have to rectify that as well.

**Comment by jonbinney** [comment]
I'm seeing similar problems. I'll try fixing them tomorrow.

**Comment by jonbinney** [comment]
I think that the color difference is actual just due to the lighting in rviz - when I orbit around to different viewpoints the colors look the same. The origins of the meshes are definiitely wrong though; working on that now.

**Comment by jonbinney** [comment]
I made some progress, but ran into another problem. link_4 shows up in the wrong place because its origin is in an odd spot. Also I had to re-convert some of the meshes, and now the colors are definitely off. Sorry for the delay; will put more time into this tomorrow.

**Comment by gavanderhoorn** [comment]
@jonbinney wrote:
> I made some progress, but ran into another problem. link_4 shows up in the wrong place because its origin is in an odd spot.

You mean that the origin of `link_4` seems to be outside of the link?

If so, that is on purpose, as that is typically where the origin is in the kinematics of the robot controller. At least for some robots. In order to allow for the greatest correspondance between urdfs and internal robot kinematics, we keep the origin there.

**Comment by jonbinney** [comment]
Yes, exactly. ok we'll keep it as is. That origin for link_4 will be at different places for the 7_70 and 5_90 then - there are two options:

- share the mesh for link_4 and handle the origin offset in the `<visual>` tag of the 7_70
- have a different mesh for link_4 of each robot, so that all the `<visual>` tags have identity for their origin.

@gavanderhoorn do you have a preference?

**Comment by gavanderhoorn** [comment]
How would you handle the different link lengths with just an offset in the `visual` tag?

Edit: I'm not near my computer, so can't check, but I seem to remember that the mesh for `link_3` is actually different, not that for `link_4`, is it?

**Comment by jonbinney** [comment]
The mesh for link_3 is different, but the origin for link_4 is outside of link_4 - it is directly above the origin of link_3. So if you want to use the same mesh for link_4 on both robots, it needs to be closer to the origin in the 5_90 - I think you could add an origin tag inside of `<visual>` to accomplish this. But it seems cleaner to just have separate meshes for link_4 on each robot.

I've finally got the meshes all in the right places, but you're right that the color is slightly off:
screenshot from 2018-03-28 18-24-36

Once I get the color matched, I'll create a new PR (squashed to avoid multiple commits of different versions of meshes).

**Comment by gavanderhoorn** [comment]
@jonbinney: have you had a chance to look at the meshes?

**Comment by jonbinney** [comment]
@gavanderhoorn I'm going to try to get them finished today.

**Comment by gavanderhoorn** [comment]
I wasn't pressuring you :) Just curious.

**Comment by jonbinney** [comment]
I fixed the mesh materials using vim (best mesh editor!). New squashed PR to replace this one: https://github.com/gavanderhoorn/abb_experimental/pull/2

**Comment by gavanderhoorn** [comment]
Closing this as replacement #2 was merged.

**Pull request closed without merging**
